<?php
/**
 * Index
 *
 * PHP version 7.3
 *
 * @category Class
 * @package  APIstax
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * APIstax
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace APIstax\Models;
use \APIstax\ObjectSerializer;

/**
 * Index Class Doc Comment
 *
 * @category Class
 * @package  APIstax
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class Index
{
    /**
     * Possible values of this enum
     */
    const AT_CPI_1 = 'at-cpi-1';

    const AT_CPI_2 = 'at-cpi-2';

    const AT_CPI_1966 = 'at-cpi-1966';

    const AT_CPI_1976 = 'at-cpi-1976';

    const AT_CPI_1986 = 'at-cpi-1986';

    const AT_CPI_1996 = 'at-cpi-1996';

    const AT_CPI_2000 = 'at-cpi-2000';

    const AT_CPI_2005 = 'at-cpi-2005';

    const AT_CPI_2010 = 'at-cpi-2010';

    const AT_CPI_2015 = 'at-cpi-2015';

    const AT_CPI_2020 = 'at-cpi-2020';

    const DE_CPI_2015 = 'de-cpi-2015';

    const AT_EU_HICP_2015 = 'at-eu-hicp-2015';

    const BE_EU_HICP_2015 = 'be-eu-hicp-2015';

    const BG_EU_HICP_2015 = 'bg-eu-hicp-2015';

    const CZ_EU_HICP_2015 = 'cz-eu-hicp-2015';

    const DK_EU_HICP_2015 = 'dk-eu-hicp-2015';

    const DE_EU_HICP_2015 = 'de-eu-hicp-2015';

    const EE_EU_HICP_2015 = 'ee-eu-hicp-2015';

    const IE_EU_HICP_2015 = 'ie-eu-hicp-2015';

    const GR_EU_HICP_2015 = 'gr-eu-hicp-2015';

    const ES_EU_HICP_2015 = 'es-eu-hicp-2015';

    const FR_EU_HICP_2015 = 'fr-eu-hicp-2015';

    const HR_EU_HICP_2015 = 'hr-eu-hicp-2015';

    const IT_EU_HICP_2015 = 'it-eu-hicp-2015';

    const CY_EU_HICP_2015 = 'cy-eu-hicp-2015';

    const LV_EU_HICP_2015 = 'lv-eu-hicp-2015';

    const LT_EU_HICP_2015 = 'lt-eu-hicp-2015';

    const LU_EU_HICP_2015 = 'lu-eu-hicp-2015';

    const HU_EU_HICP_2015 = 'hu-eu-hicp-2015';

    const MT_EU_HICP_2015 = 'mt-eu-hicp-2015';

    const NL_EU_HICP_2015 = 'nl-eu-hicp-2015';

    const PL_EU_HICP_2015 = 'pl-eu-hicp-2015';

    const PT_EU_HICP_2015 = 'pt-eu-hicp-2015';

    const RO_EU_HICP_2015 = 'ro-eu-hicp-2015';

    const SI_EU_HICP_2015 = 'si-eu-hicp-2015';

    const SK_EU_HICP_2015 = 'sk-eu-hicp-2015';

    const FI_EU_HICP_2015 = 'fi-eu-hicp-2015';

    const SE_EU_HICP_2015 = 'se-eu-hicp-2015';

    const IS_EU_HICP_2015 = 'is-eu-hicp-2015';

    const NO_EU_HICP_2015 = 'no-eu-hicp-2015';

    const CH_EU_HICP_2015 = 'ch-eu-hicp-2015';

    const GB_EU_HICP_2015 = 'gb-eu-hicp-2015';

    const MK_EU_HICP_2015 = 'mk-eu-hicp-2015';

    const RS_EU_HICP_2015 = 'rs-eu-hicp-2015';

    const TR_EU_HICP_2015 = 'tr-eu-hicp-2015';

    const US_EU_HICP_2015 = 'us-eu-hicp-2015';

    const EA_EU_HICP_2015 = 'ea-eu-hicp-2015';

    const EEA_EU_HICP_2015 = 'eea-eu-hicp-2015';

    const EU_EU_HICP_2015 = 'eu-eu-hicp-2015';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::AT_CPI_1,
            self::AT_CPI_2,
            self::AT_CPI_1966,
            self::AT_CPI_1976,
            self::AT_CPI_1986,
            self::AT_CPI_1996,
            self::AT_CPI_2000,
            self::AT_CPI_2005,
            self::AT_CPI_2010,
            self::AT_CPI_2015,
            self::AT_CPI_2020,
            self::DE_CPI_2015,
            self::AT_EU_HICP_2015,
            self::BE_EU_HICP_2015,
            self::BG_EU_HICP_2015,
            self::CZ_EU_HICP_2015,
            self::DK_EU_HICP_2015,
            self::DE_EU_HICP_2015,
            self::EE_EU_HICP_2015,
            self::IE_EU_HICP_2015,
            self::GR_EU_HICP_2015,
            self::ES_EU_HICP_2015,
            self::FR_EU_HICP_2015,
            self::HR_EU_HICP_2015,
            self::IT_EU_HICP_2015,
            self::CY_EU_HICP_2015,
            self::LV_EU_HICP_2015,
            self::LT_EU_HICP_2015,
            self::LU_EU_HICP_2015,
            self::HU_EU_HICP_2015,
            self::MT_EU_HICP_2015,
            self::NL_EU_HICP_2015,
            self::PL_EU_HICP_2015,
            self::PT_EU_HICP_2015,
            self::RO_EU_HICP_2015,
            self::SI_EU_HICP_2015,
            self::SK_EU_HICP_2015,
            self::FI_EU_HICP_2015,
            self::SE_EU_HICP_2015,
            self::IS_EU_HICP_2015,
            self::NO_EU_HICP_2015,
            self::CH_EU_HICP_2015,
            self::GB_EU_HICP_2015,
            self::MK_EU_HICP_2015,
            self::RS_EU_HICP_2015,
            self::TR_EU_HICP_2015,
            self::US_EU_HICP_2015,
            self::EA_EU_HICP_2015,
            self::EEA_EU_HICP_2015,
            self::EU_EU_HICP_2015
        ];
    }
}


