on:
  - push

name: Test

jobs:
  run:
    name: Tests

    strategy:
      matrix:
        php-versions: ['7.3', '7.4', '8.0', '8.1']

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: sockets, json, curl

      - name: Install dependencies with composer
        run: composer install

      - name: Test with phpunit
        run: vendor/bin/phpunit